### ISSUE TITLE
support tls connections

### ISSUE THREAD

**Issue by vadimi** [vadimi/grpc-client-cli#12]
We need to add options to the cli to support tls connections: `--tls`. Mutual tls also needs to be supported.

- [x] grpc tls connection
- [ ] eureka secure port usage

**Comment by jhaygood86** [comment]
As part of this, Eureka resolver needs to be enhanced to use secure port.

**Comment by vadimi** [comment]
hey @jhaygood86 I'd like to release version `1.2.0` of the cli. Do you want to add that Eureka change before I do that?

**Comment by jhaygood86** [comment]
Go ahead and release. I'll try and find some time this or next week and we can do 1.2.1?

**Comment by vadimi** [comment]
sounds good, I'll keep this issue open then.

**Comment by vadimi** [comment]
Closing this one in favour of #32
