### ISSUE TITLE
please explain the error message 

### ISSUE THREAD

**Issue by Agent-Hellboy** [vadimi/grpc-client-cli#126]
Hi, what does below error mean ?

`rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded`

**Comment by vadimi** [comment]
hello, the error is coming from grpc-go connectivity code - it means that it failed to connect to the service, most likely it's not accessible

**Comment by Agent-Hellboy** [comment]
> received context error while waiting for new LB policy update:

THis seems too internal , is it that load balancer is not able to pick a channel ? what is it? I am able to ping my grpc server port , btw it worked fine for one of my grpc server , Thanks for the amazing tool

**Comment by Agent-Hellboy** [comment]
Hi @vadimi  does the tool support secure mode? Does it require an SSH key or any other configuration for TLS? It's possible the error is related to running it in secure mode.

**Comment by vadimi** [comment]
yes, it does, if you run it with `grpc-client-cli --help` it will show the flags you need to pass: `--tls`, `--cert`, `--certkey` depending on your use case

**Comment by vadimi** [comment]
closing the issue for now, let me know if you have other questions
