### ISSUE TITLE
Request to wrap the binary as python package and upload it to pypi 

### ISSUE THREAD

**Issue by Agent-Hellboy** [vadimi/grpc-client-cli#127]
Hey, what are your thoughts on packaging it as a Python package? Let’s say, for some reason, someone doesn’t want to install Go just to test the reflection service. Since Python is commonly pre-installed on Linux distributions (as many Linux tools rely on it), this could simplify things for users.

I can raise a PR , if you want

**Comment by vadimi** [comment]
hey, not sure about what it takes to support python package. Technically Go installation is not required as I publish binaries with every release - https://github.com/vadimi/grpc-client-cli/releases/tag/v1.21.1

would that help?

**Comment by Agent-Hellboy** [comment]
Yeah, Thanks
