### ISSUE TITLE
Netflix Eureka integration

### ISSUE THREAD

**Issue by jhaygood86** [vadimi/grpc-client-cli#2]
I already have the code (locally), but wouldn't mind coming up with a good design to integrate it upstream.

essential idea is that your grpc target is in URI format like this: eureka://service-name/
Some options that would be needed is the Eureka endpoint (though defaulting to http://localhost:8167/eureka/ should be fine, the ability to use a different endpoint would be required)

I'm thinking this: grpc-client-cli eureka://service-name/,registry=http://registry:8167

I'm very open to suggestions to improve this, but it'd be nice to have this upstream (versus just on my laptop)

**Comment by vadimi** [comment]
One of the options would be to implement a custom resolver for eureka: https://github.com/grpc/grpc-go/tree/master/resolver and register eureka:// schema name there. Custom resolver will allow you to perform re-resolution periodically and enable client side load balancing.

Then you can have urls similar to this one: `eureka://registry:8167/service-name`

**Comment by jhaygood86** [comment]
Please see Pull Request #3 -- uses URL structure you proposed (which is actually natively supported by grpc apparently)

**Comment by vadimi** [comment]
Very cool, thanks. I’m out of town for a few days, will review it on Tuesday.

**Comment by vadimi** [comment]
resolved by #3
