### ISSUE TITLE
Handle input in protobuf debug format

### ISSUE THREAD

**Issue by netdragonboberb** [vadimi/grpc-client-cli#24]
@jhaygood86 and I talked about adding functionality to handle protobuf debug format like the following from a dump from Java. It's quite a bit of work to convert it. Perhaps either auto-detect of through a flag, or a seperate command line parameter to convert it and dump the converted output (would probably be the easiest). This will be tracked against for adding it.

`
object1 {
  object_uid: "e0166542-24be-4077-88fa-a8755df766d1"
  values {
    valuea {
      currency_code: "USD"
      units: 100
    }
    valueb {
      currency_code: "USD"
      units: 85
    }
  }
  }
`

**Comment by vadimi** [comment]
yeah, it should be possible to support "protobuf text" format. Do you want to support it in input and output?

**Comment by vadimi** [comment]
hey @netdragonboberb give this branch a try [feature/proto-text](https://github.com/vadimi/grpc-client-cli/tree/feature/proto-text). I've added `-format` option that accepts `text` or `json`, `json` is the default

**Comment by vadimi** [comment]
@netdragonboberb are you still interested in this functionality?

**Comment by netdragonboberb** [comment]
Hi @vadimi definately. I just haven't had a chance yet to set up Go on my new computer and build it. I'll try to get that over the week. If you have a binary of it, I can try it out.

**Comment by netdragonboberb** [comment]
@vadimi Linux binary, I mean

**Comment by netdragonboberb** [comment]
@vadimi Is the "oneof" functionality #7 on the same branch?

**Comment by netdragonboberb** [comment]
@vadimi disregard. I see that they are different branches. I'll combine them when I test it out.

**Comment by netdragonboberb** [comment]
Hi @vadimi I tested, and when I did -format text I also got text output. Can we have -inputformat and -outputformat?
e.g.
grpc-client-cli -s com.xx.xx.SuperService -m SuperMethod x.x.x.x:xxxx -inputformat text -outputformat json -i dump.txt

**Comment by netdragonboberb** [comment]
@vadimi I may be able to do this. I think I just edit the caller to resultPrinter ?

**Comment by netdragonboberb** [comment]
@vadimi I started it here https://github.com/netdragonboberb/grpc-client-cli/tree/bb/proto-combined then I got stuck because no matter what I did, the output is still in text when I do -outformat json  I even see "Output format: json" in the print message I created.  Can you tell what I'm doing wrong? (I'm just tackling non-streaming for now)

**Comment by vadimi** [comment]
hey @netdragonboberb, yeah `-informat` and `-outformat` are looking good as options.

the reason you're still getting text instead of json is `caller.NewServiceCaller(a.connFact, a.opts.InFormat)`. ServiceCaller performs marshalling and unmarshalling as well, and it uses `a.opts.InFormat`, you'd need to add another parameter to `NewServiceCaller` that will accept `a.opts.OutFormat`

**Comment by netdragonboberb** [comment]
@vadimi Justin is starting to use this functionality so I think we should close this ticket and I'll create a new one for the enhancement I  described

**Comment by vadimi** [comment]
@netdragonboberb ok, I can work on this
