### ISSUE TITLE
Enhance -format option - allow splitting of input and output

### ISSUE THREAD

**Issue by netdragonboberb** [vadimi/grpc-client-cli#28]
Split from #24 
1. Add new -inputformat and -outputformat
2. Make sure -format is still supported as a shortcut to -inputformat and -outputformat being the same (the branch I created will need to be updated for that)

Discussion from #24 

Collaborator Author
netdragonboberb commented 26 days ago

Hi @vadimi I tested, and when I did -format text I also got text output. Can we have -inputformat and -outputformat?
e.g.
grpc-client-cli -s com.xx.xx.SuperService -m SuperMethod x.x.x.x:xxxx -inputformat text -outputformat json -i dump.txt
@netdragonboberb
Collaborator Author
netdragonboberb commented 26 days ago •

@vadimi I may be able to do this. I think I just edit the caller to newResultPrinter and then add the new options?
@netdragonboberb
Collaborator Author
netdragonboberb commented 26 days ago •

@vadimi I started it here https://github.com/netdragonboberb/grpc-client-cli/tree/bb/proto-combined then I got stuck because no matter what I did, the output is still in text when I do -outformat json I even see "Output format: json" in the print message I created. If both informat and outformat match, it works as expected. Can you tell what I'm doing wrong? (I'm just tackling non-streaming for now)

You can see a diff here https://github.com/netdragonboberb/grpc-client-cli/pull/3/files
@vadimi
Owner
vadimi commented 26 days ago

hey @netdragonboberb, yeah -informat and -outformat are looking good as options.

the reason you're still getting text instead of json is caller.NewServiceCaller(a.connFact, a.opts.InFormat). ServiceCaller performs marshalling and unmarshalling as well, and it uses a.opts.InFormat, you'd need to add another parameter to NewServiceCaller that will accept a.opts.OutFormat

**Comment by vadimi** [comment]
Closed via #29
