### ISSUE TITLE
servicemeta_proto-GetServiceMetaDataList context parameter is useless

### ISSUE THREAD

**Issue by Maccoray** [vadimi/grpc-client-cli#38]
in internal/caller/servicemeta_proto.go on 32 line
func (smp *serviceMetadataProto) GetServiceMetaDataList(**ctx context.Context**) ([]*ServiceMeta, error) {
ctx is unnecessary.

**Comment by vadimi** [comment]
it implements `ServiceMetaData` interface, so it has to be there

**Comment by Maccoray** [comment]
ok,get it,thx~
