### ISSUE TITLE
Include default google protobuf

### ISSUE THREAD

**Issue by rodoufu** [vadimi/grpc-client-cli#41]
In my protobuf files I have imports like this:
```proto
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
```

When I try to call the tool it answers with:
```sh
$ grpc-client-cli --address localhost:9101 --proto path/my.proto 
error parsing proto files: my.proto:7:8: open path/google/api/annotations.proto: no such file or directory
```

It could have an option to automatically include that.
Those come from:
- https://github.com/protocolbuffers/protobuf/tree/main/src/google
- https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-openapiv2

**Comment by rodoufu** [comment]
Yes, it is good to know, thank you very much.

What about stuff under `google/api` and `protoc-gen-openapiv`?
That is used by https://github.com/grpc-ecosystem/grpc-gateway to generate a HTTP gateway for your gRPC endpoints, it is quite useful.

**Comment by vadimi** [comment]
I don't have immediate plans to embed anything else except well-known types. Considering you can still pass them using `--protoimports` option it shouldn't be a blocker.

**Comment by rodoufu** [comment]
@vadimi it is not a blocker.
It was very good to know that the lib already includes the must used ones, it solves most of the cases.
Thank you very much for the tool and your quick response.
Would you be open to a change like that as a pull request?
