### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by VeljkoMaksimovic** [vadimi/grpc-client-cli#45]
Hi guys, are there any plans for m1(arm) support?

**Comment by vadimi** [comment]
hello, it is supported already - there is an arm64 build for macos (grpc-client-cli_darwin_arm64.tar.gz) or you can run `go install github.com/vadimi/grpc-client-cli/cmd/grpc-client-cli@v1.13.1`

**Comment by VeljkoMaksimovic** [comment]
Thanks
