### ISSUE TITLE
how to use protoimports

### ISSUE THREAD

**Issue by ernest-ag5** [vadimi/grpc-client-cli#46]
```
grpc-client-cli \
		--proto /Users/me/Projects/my-apis/src/proto/my/protobuf/scorn/v1 \
		--protoimports /Users/me/Projects/my-apis/src/proto/my/protobuf/common/v1 \
		services.mine.io:443 
```
exits with an error
```
error parsing proto files: scorn-sync.proto:7:8: open /Users/me/Projects/my-apis/src/proto/my/protobuf/scorn/v1/my/protobuf/common/v1/common.proto: no such file or directory
```
Inside scorn/v1, we have a proto file with import 
```
import "my/protobuf/common/v1/common.proto";
```
So my question is , what is the correct parameter here?

**Comment by vadimi** [comment]
try using `--protoimports /Users/me/Projects/my-apis/src/proto`

**Comment by ernest-ag5** [comment]
is replies:  
```
error parsing additional proto files: no proto files found in 
```

**Comment by vadimi** [comment]
hm, alright, will look into it

**Comment by vadimi** [comment]
I might have a fix for this in https://github.com/vadimi/grpc-client-cli/tree/feature/recursive-proto-search. The build is here https://app.circleci.com/pipelines/github/vadimi/grpc-client-cli/250/workflows/773a19bd-6145-42b7-928b-0eb65b232e96/jobs/279/artifacts

and the command line params are simplified for this call in the new build:

```
grpc-client-cli \
		--proto /Users/me/Projects/my-apis/src/proto \
		services.mine.io:443 
```
this one should work now too:
```
grpc-client-cli \
		--proto /Users/me/Projects/my-apis/src/proto/my/protobuf/scorn/v1 \
		--protoimports /Users/me/Projects/my-apis/src/proto \
		services.mine.io:443 
```
if it works for you I will release the new version of the cli
