### ISSUE TITLE
the result is not camelCase

### ISSUE THREAD

**Issue by qazwsxedckll** [vadimi/grpc-client-cli#48]
```
message Test{
	string test_test = 1;
}

//  result
{
	"test_test": "test"
}
```

It should be
```
{
	"testTest": "test"
}
```
according to https://developers.google.com/protocol-buffers/docs/proto3#json

> Generates JSON objects. Message field names are mapped to lowerCamelCase and become JSON object keys. If the json_name field option is specified, the specified value will be used as the key instead. Parsers accept both the lowerCamelCase name (or the one specified by the json_name option) and the original proto field name. null is an accepted value for all field types and treated as the default value of the corresponding field type.

json_name option is not working too.

**Comment by vadimi** [comment]
yes, the tool is ignoring this option and using original proto names only. if you're interested in camel case results I can add another command line switch to do it.

**Comment by vadimi** [comment]
@qazwsxedckll I've added an optional flag `out-json-names` to use camel casing in the output, will release new version of the tool in a few days
