### ISSUE TITLE
--service option does not seem to work

### ISSUE THREAD

**Issue by NikolaBorisov** [vadimi/grpc-client-cli#49]
I tried using the --service option and passed both the long and short service. I get an error that the service name is invalid. When I run without the --service option it asks to pick a service. I copied the exact name from there but It still doesn't work.

Trying to do something like this
```
grpc-client-cli localhost:5000 -s TestService -m hello
```

**Comment by vadimi** [comment]
Could you provide your proto file? I can check then what’s going on

**Comment by vadimi** [comment]
I also see that the order of parameters is not what the tool expects. It should be 

```
grpc-client-cli -s TestService -m hello localhost:5000
```
or
```
grpc-client-cli -a localhost:5000 -s TestService -m hello
```

**Comment by NikolaBorisov** [comment]
@vadimi thanks the argument order was the issue... The tool is good :)
