### ISSUE TITLE
Eureka resolver should use sane default port

### ISSUE THREAD

**Issue by jhaygood86** [vadimi/grpc-client-cli#5]
Eureka should use the same default port for remote Eureka servers as local Eureka instances.

If no one volunteers, I'll take care of this tomorrow and push a 1.0.1 release.

**Comment by vadimi** [comment]
@jhaygood86 go ahead, I've added circlecli support so it should automatically build and release when you add a tag, just follow the existing naming convention - `v1.0.1`
