### ISSUE TITLE
Imports does not work

### ISSUE THREAD

**Issue by adriantabirta** [vadimi/grpc-client-cli#52]
I my proto files:

```
import "google/protobuf/Empty.proto";
...
```

I run in terminal (on linux, libprotoc 3.12.4):

`grpc-client-cli --proto /path/to/proto/files localhost:9000`

And got: 

`error parsing proto files: [File name] .../google/protobuf/Empty.proto: no such file or director`

It is possible to add support for imported local & remote proto files or am I doing smth wrong?

**Comment by vadimi** [comment]
closing for now, feel free to reopen if new information appears
