### ISSUE TITLE
Error: Unexpected <class 'AttributeError'>: 'NoneType' object has no attribute 'unary_unary'

### ISSUE THREAD

**Issue by NikolaBorisov** [vadimi/grpc-client-cli#56]
On 1.17 I get this error:

```
grpc-client-cli --insecure 10.100.194.194:7000
rpc error: code = Unknown desc = Unexpected <class 'AttributeError'>: 'NoneType' object has no attribute 'unary_unary'
```

1.15 works fine

**Comment by vadimi** [comment]
hm, it looks like the issue is coming from the python grpc service. Any chance you can provide a minimal example that reproduces the issue?

**Comment by vadimi** [comment]
I've tried to reproduce it with a simple python service and it worked for me just fine. Without seeing the code I can only assume it could be something in your service that throws this error.

**Comment by vadimi** [comment]
thanks for this, I was able to reproduce the issue. It's a combination of grpc with asyncio + that interceptor that you mentioned causes it. As soon as I remove the interceptor it works fine. Not sure what's going on, will check

**Comment by vadimi-ep** [comment]
ok, I was able to figure it out. Unfortunately `grpc-interceptor` does not somehow fully support asyncio/grpc spec and does not return Unimplemented error that the cli expects when it's trying to pick the right grpc reflect version. The PR above changes this behavior, which should fix the issue with your python interceptor. I'll release the new version soon.

**Comment by vadimi** [comment]
ok, I was able to figure it out. Unfortunately `grpc-interceptor` does not somehow fully support asyncio/grpc spec and does not return Unimplemented error that the cli expects when it's trying to pick the right grpc reflect version. The PR above changes this behavior, which should fix the issue with your python interceptor. I'll release the new version soon.

**Comment by NikolaBorisov** [comment]
Thank your
