### ISSUE TITLE
[Question] How to add metadata to requests?

### ISSUE THREAD

**Issue by quanta-kt** [vadimi/grpc-client-cli#59]
I would like to make an authorized request to a gRPC service, which requires me to send a JWT token
in the request metadata.
I don't see an option to add metadata in help, is this supported?

**Comment by quanta-kt** [comment]
I tried doing 
```sh
./grpc-client-cli --proto /proto/path/ myservice.co:50051 -H "Authorization: bearer token"
```
> Error: rpc error: code = Unauthenticated desc = rpc error: code = Unauthenticated desc = Request unauthenticated with bearer

**Comment by vadimi** [comment]
so the order of parameters matters in the cli. If you don't specify `--addr` then the service address needs to be the last param. Or just try this: `./grpc-client-cli --proto /proto/path/ --addr myservice.co:50051 -H "Authorization: bearer token"`

**Comment by vadimi** [comment]
feel free to reopen if there is still an issue
