### ISSUE TITLE
Seems like custom Headers are not sent

### ISSUE THREAD

**Issue by LucaReggiannini** [vadimi/grpc-client-cli#65]
Hello

I'm testing a demo service. It exposes a method to register new users. It returns an ID inside the JSON response and a token inside an extra Header called "token" (nothing in production so it's safe to show).
```
sudo tcpdump -A -i any port 50051 | grep token
    tcpdump: data link type LINUX_SLL2
    tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
    listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
    .Your id is 687.............token..b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoia2FsaSIsImV4cCI6MTY5MDY2MDEwMn0.UyNVRd-jCCvcf_oCoNA1M2-Fi0i0_vtGUNqIsz1QxRA'.............

```

I need to send the token back:
```
echo '{"id":"678"}' | grpc-client-cli --service demoApp --method getInfo --header "token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoia2FsaSIsImV4cCI6MTY5MDY2MDEwMn0.UyNVRd-jCCvcf_oCoNA1M2-Fi0i0_vtGUNqIsz1QxRA'" 192.168.0.100:50051
{
  "message": "Authorization Error.Missing 'token' header"
}
```

Seems like the token is never sent over the network. I tested various forms without success:
```
-H "token: b'xxxyyy'"
-H "token: xxxyyy"
-H "token: 'xxxyyy'"
-H "Authorization: xxxyyy"
...
```

I tried to send an unique string to see if it's transmitted: 
```
echo '{"a":"b"}' | grpc-client-cli --service demoApp --method getInfo --header "myuniquestring: value123" 192.168.0.100:50051

sudo tcpdump -A -i any port 50051 | grep myuniquestring
```

The header is never transmitted. Maybe i'm missing something obvious.

I looked into the source code to find out what's the problem without any success.

Is there any additional information i can submit to debug this issue?

**Comment by vadimi** [comment]
Hello, I just checked and I can definitely see the header sent via `--header` or `-H` using the latest code:
```
echo '{}' | ./grpc-client-cli --service grpc.health.v1.Health --method Check --header "test-header: value" localhost:50031
```
<img width="1057" alt="image" src="https://github.com/vadimi/grpc-client-cli/assets/1156106/1e12227f-4e9e-4a31-9ccd-a6160ba76739">

Could you share how you read the header on the receiving end?

**Comment by vadimi** [comment]
by the way analyzing binary `http/2` traffic using tcpdump is kind of tricky, I recommend Wireshark (the screenshot above)

**Comment by LucaReggiannini** [comment]
Hello. Sorry for the delay. After some analysis i discovered that there was i problem in my side (the custom code i was testing). Additionally, i can confirm that the Headers are sent correctly over the net. Thanks for your time <3
