### ISSUE TITLE
oneof not displayed when you type '?' after choosing the method

### ISSUE THREAD

**Issue by netdragonboberb** [vadimi/grpc-client-cli#7]
If you put a oneof in your request data, it is not displayed when you go to the service, choose the method, and click '?'

I'm not sure if it's specific to the message (doubt it) so I gave a sample of the actual message with names changed.

message SampleRequest {
    MyEntity entity = 1;
    oneof inputs_oneof {
        MyInputs current_bill_inputs = 2;
        MyInputs ytd_inputs = 3;
    }
    int64 foo = 4;
    repeated MyData data_rows = 5;
}

Example:
Message json (type ? to see defaults): ?
{"entity":null,"foo":"0","data_rows":[]}

**Comment by vadimi** [comment]
@netdragonboberb yeah, default message generator is not super smart - it does not support arrays or child messages, but how would you actually represent oneof in json?

**Comment by netdragonboberb** [comment]
@vadimi 
I'm thinking we represent it like this or equivalent with a little note at the bottom:
`
{"entity": null, "current_bill_inputs | ytd_inputs": null, foo: "", data_rows: ""}

Additional syntax warnings:
This message contains a "oneof" which allows only one value in the message or unexpected results could occur depending on the gRPC version on the server.
`

Sadly, the spec isn't exactly clear, yet.I've seen people talk about two approaches: placing it directly on the message, or nested messages. I've seen placing it on the message work and skeptical about the nested approach. 

The new "field presence" functionality may provide some info but I don't know if it's consistent with older versions but I think at least with gRPC 3 it's worked? It implies that you could theoretically have more than one field from the oneof in a message and the last to appear in the message wins. https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md
```

When deserializing, duplicate field values may be handled in different ways depending on the field definition.
Duplicate repeated fields are typically appended to the field's API representation. (Note that serializing a packed repeated field produces only one, length-delimited value in the tag stream.)
Duplicate optional field values follow the rule that "the last one wins."
oneof fields expose the API-level invariant that only one field is set at a time. However, the wire format may include multiple (tag, value) pairs which notionally belong to the oneof. Similar to optional fields, the generated API follows the "last one wins" rule.
Out-of-range values are not returned for enum fields in generated proto2 APIs. However, out-of-range values may be stored as unknown fields in the API, even though the wire-format tag was recognized.
```

There's also:
https://github.com/golang/protobuf/issues/283
and goings-on there may give some clarity

**Comment by vadimi** [comment]
hey @netdragonboberb, here is another idea that we discussed with @jhaygood86 today. We can support more commands, not just `?` to do various actions. I've added `??` command to print entire message proto instead of json with defaults. Give it a try in this branch and let me know your thoughts: [experiment-proto-print](https://github.com/vadimi/grpc-client-cli/tree/feature/experiment-proto-print). We can change the command to be more user friendly, this is just an experiment.

**Comment by netdragonboberb** [comment]
Thanks. I'll check it out shortly.

**Comment by vadimi** [comment]
hey @netdragonboberb any updates on that, did it help?

**Comment by netdragonboberb** [comment]
@vadimi I'm going to combine the two branches and test together.

**Comment by netdragonboberb** [comment]
@vadimi It worked! Excerpt below with names scrubbed.
`
boberb@localhost grpc-client-cli]$ grpc-client-cli x.x.x.x:xxxxx
? Choose a service: x.x.x.x.x.SuperSecretName
? Choose a method: GetObjectThatNotBeNamed
Message json (type ? to see defaults): ??
message GetObjectThatNotBeNamedRequest {
  google.protobuf.Int64Value secret_id = 1;

  oneof SecretObject {
    google.protobuf.Int64Value secret_type_2_id = 2;

    SecretObjectDescriptor secret_type_3 = 3;

    google.protobuf.Int64Value secret_type_4_id = 4;

    SecretObjectDescriptorLegacy secret_type_legacy = 6;
  }

  bool find_best_secret_object = 5;

  google.type.Date date = 7;
}

`

**Comment by vadimi** [comment]
@netdragonboberb awesome, thanks for testing. do you like `??` command? Maybe something more descriptive would work better? like `proto` ?
