### ISSUE TITLE
Windows path delimiter causing "error parsing proto files: open products.proto: The system cannot find the file specified."

### ISSUE THREAD

**Issue by mtsfoni** [vadimi/grpc-client-cli#88]
The tool seems not be able to handle backslashes in paths on Windows:

This is not working
```
PS C:\Users\User> grpc-client-cli --proto "E:\src\CompanyName\ERP.Prototype.Backend\Prototype\ERP.Backend.gRPC\Protos\products.proto" localhost:5140
error parsing proto files: open products.proto: The system cannot find the file specified.
```

This does work:
```
PS C:\Users\User> grpc-client-cli --proto "E:/src/CompanyName/ERP.Prototype.Backend/Prototype/ERP.Backend.gRPC/Protos/products.proto" localhost:5140
? Choose a service:  [Use arrows to move, type to filter]
→ products.ProductService
```

Expected behaviour: 
Since backslashes are the normal path delimiter in windows, I expect the client to be able to open the file.
As a minimal solution, the error message could be more helpful by e.g. repeating the path, so the user might see that the grpc-client has problems with backslashes. Or just add a static hint when the file is not found.

**Comment by vadimi** [comment]
thanks for reporting, should be fixed now
